In [1]:
import numpy as np

In [2]:
#Cria uma matriz
np.array([10,20,30,40,50,100,400])

array([ 10,  20,  30,  40,  50, 100, 400])

In [3]:
#tipo 
type([])

list

In [4]:
type({})

dict

In [5]:
dados = np.array(
    [[10,9,8,7,6],
    [5,4,3,2,1]]
)

print(dados)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [6]:
tres = np.array([
    [15,14,13,11],
    [10,20,30,40,50],
    [5,4,6,7,8]
])
print(tres)

[list([15, 14, 13, 11]) list([10, 20, 30, 40, 50]) list([5, 4, 6, 7, 8])]


C:\Users\walla\AppData\Local\Temp\ipykernel_93260\1221309157.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tres = np.array([


In [7]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
#Experimento de Processamento 
Estressando_NP =np.arange(100000)
len(Estressando_NP)

100000

In [9]:
%time for loop in Estressando_NP: pass

CPU times: total: 15.6 ms
Wall time: 15.4 ms


In [10]:
for loop in range(10):
    print(loop)

0
1
2
3
4
5
6
7
8
9


In [11]:
#Acessar os arrays 
Array[0]

NameError: name 'Array' is not defined